// use `AUTH.<name>` prefix for most cases

export const AUTH_ERROR = {
    READ_ONLY_MODE_ENABLED: 'READ_ONLY_MODE_ENABLED',
    DB_UNIQUE_VIOLATION: 'AUTH.DB.UNIQUE_VIOLATION',
    NUMERIC_VALUE_OUT_OF_RANGE: 'AUTH.DB.NUMERIC_VALUE_OUT_OF_RANGE',
    VALIDATION_ERROR: 'AUTH.VALIDATION_ERROR',
    USER_ALREADY_EXISTS: 'AUTH.USER_ALREADY_EXISTS',
    NEED_RESET: 'AUTH.NEED_RESET',
    ACCESS_DENIED: 'AUTH.ACCESS_DENIED',
    USER_NOT_EXISTS: 'AUTH.USER_NOT_EXISTS',
    OLD_PASSWORD_INCORRECT: 'AUTH.OLD_PASSWORD_INCORRECT',
    ROLE_NOT_EXISTS: 'AUTH.ROLE_NOT_EXISTS',
    NOT_CONSISTENT: 'AUTH.NOT_CONSISTENT',
    IDP_USER_CHANGE_NOT_ALLOWED: 'AUTH.IDP_USER_CHANGE_NOT_ALLOWED',
    MANAGE_LOCAL_USERS_DISABLED: 'AUTH.MANAGE_LOCAL_USERS_DISABLED',
    SIGNUP_DISABLED: 'AUTH.SIGNUP_DISABLED',
    INVALID_AUTH_COOKIE_ENDPOINT: 'AUTH.INVALID_AUTH_COOKIE_ENDPOINT',
    OIDC_DISABLED: 'AUTH.OIDC.DISABLED',
    OIDC_MISCONFIGURED: 'AUTH.OIDC.MISCONFIGURED',
    OIDC_PROVIDER_UNAVAILABLE: 'AUTH.OIDC.PROVIDER_UNAVAILABLE',
    OIDC_INVALID_TRANSACTION: 'AUTH.OIDC.INVALID_TRANSACTION',
    OIDC_AUTHORIZATION_FAILED: 'AUTH.OIDC.AUTHORIZATION_FAILED',
    OIDC_INVALID_CLAIMS: 'AUTH.OIDC.INVALID_CLAIMS',
    OIDC_GROUP_NOT_ALLOWED: 'AUTH.OIDC.GROUP_NOT_ALLOWED',
};

export const READ_ONLY_MODE_CODE = 451;
